#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 25' size 6, 4
set output "hmc_transition_cartoon.eps"

unset border

unset xtics
set xrange[-5:5]

unset ytics
set yrange[-5:5]

set arrow from -4.75, 0 to 4.75, 0 lw 2 lc rgb "black" nohead back
set label "q" at 5, 0 center

set arrow from 0, -4.75 to 0, 4.75 lw 2 lc rgb "black" nohead back
set label "p" at 0, -5 center

set arrow from 3 * cos(0.8 * pi), 0 to 3 * cos(0.8 * pi), 3 * sin(0.8 * pi) lw 3 lc rgb "$light" \
head filled size screen 0.01, 35 front
set arrow from 3 * cos(0.55 * pi), 3 * sin(0.55 * pi) to 3 * cos(0.55 * pi), 0.1 lw 3 lc rgb "$light" \
head filled size screen 0.01, 35 front

set arrow from 3 * cos(0.55 * pi) - 0.1, 3 * sin(0.55 * pi) - 0.02 \
to 3 * cos(0.55 * pi), 3 * sin(0.55 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set obj circle at 3 * cos(0.8 * pi), 0 size 0.075 fs solid fc rgb "$light" front
set obj circle at 3 * cos(0.55 * pi), 0 size 0.075 fs solid fc rgb "$light" front

set samples 100    # X Samples for ++
set isosamples 100  # Y Samples for ++

cos_seg(x, th1, dth) = cos( dth * (x + 5) / 10.0 + th1)
sin_seg(x, th1, dth) = sin( dth * (x + 5) / 10.0 + th1)

plot \
'+' using (3.0 * cos_seg(\$1, 0.8 * pi, -0.25 * pi)):(3.0 * sin_seg(\$1, 0.8 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 6, 4
set output "hmc_chain_cartoon1.eps"

unset border

unset xtics
set xrange[-5:5]

unset ytics
set yrange[-5:5]

set arrow from -4.75, 0 to 4.75, 0 lw 2 lc rgb "black" nohead back
set label "q" at 5, 0 center

set arrow from 0, -4.75 to 0, 4.75 lw 2 lc rgb "black" nohead back
set label "p" at 0, -5 center


set obj ellipse at 0, 0 size 1.0, 1.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 2.0, 2.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 3.0, 3.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 4.0, 4.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 5.0, 5.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 6.0, 6.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 7.0, 7.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 8.0, 8.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 9.0, 9.0 lw 5 fs empty border lc rgb "#D3D3D3"

set arrow from 3 * cos(0.8 * pi), 0 to 3 * cos(0.8 * pi), 3 * sin(0.8 * pi) lw 3 lc rgb "$light" nohead front
set arrow from 3 * cos(0.55 * pi), 0 to 3 * cos(0.55 * pi), 3 * sin(0.55 * pi) lw 3 lc rgb "$light" nohead front
set arrow from 1 * cos(0.4 * pi), 0 to 1 * cos(0.4 * pi), 4.225 * sin(0.4 * pi) lw 3 lc rgb "$light" nohead front
set arrow from 4 * cos(0.225 * pi), 0 to 4 * cos(0.225 * pi), 4 * sin(0.225 * pi) lw 3 lc rgb "$light" nohead front
set arrow from 3.5 * cos(-0.085 * pi), 0 to 3.5 * cos(-0.085 * pi), 3.5 * sin(-0.085 * pi) lw 3 lc rgb "$light" nohead front

set arrow from 3 * cos(0.55 * pi) - 0.1, 3 * sin(0.55 * pi) - 0.02 \
to 3 * cos(0.55 * pi), 3 * sin(0.55 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set arrow from 1 * cos(0.4 * pi) - 0.1, 1 * sin(0.4 * pi) + 0.0275 \
to 1 * cos(0.4 * pi), 1 * sin(0.4 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set arrow from 4 * cos(0.225 * pi) - 0.1, 4 * sin(0.225 * pi) + 0.115 \
to 4 * cos(0.225 * pi), 4 * sin(0.225 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set arrow from 3.5 * cos(-0.085 * pi) + 0.06, 3.5 * sin(-0.085 * pi) + 0.25 \
to 3.5 * cos(-0.085 * pi), 3.5 * sin(-0.085 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set obj circle at 3 * cos(0.8 * pi), 0 size 0.075 fs solid fc rgb "$light" front
set obj circle at 3 * cos(0.55 * pi), 0 size 0.075 fs solid fc rgb "$light" front
set obj circle at 1 * cos(0.4 * pi), 0 size 0.075 fs solid fc rgb "$light" front
set obj circle at 4 * cos(0.225 * pi), 0 size 0.075 fs solid fc rgb "$light" front
set obj circle at 3.5 * cos(-0.085 * pi), 0 size 0.075 fs solid fc rgb "$light" front

set samples 100    # X Samples for ++
set isosamples 100  # Y Samples for ++

cos_seg(x, th1, dth) = cos( dth * (x + 5) / 10.0 + th1)
sin_seg(x, th1, dth) = sin( dth * (x + 5) / 10.0 + th1)

plot \
'+' using (3.0 * cos_seg(\$1, 0.8 * pi, -0.25 * pi)):(3.0 * sin_seg(\$1, 0.8 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle, \
'+' using (1.0 * cos_seg(\$1, 0.65 * pi, -0.25 * pi)):(1.0 * sin_seg(\$1, 0.65 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle, \
'+' using (4.0 * cos_seg(\$1, 0.475 * pi, -0.25 * pi)):(4.0 * sin_seg(\$1, 0.475 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle, \
'+' using (3.5 * cos_seg(\$1, 0.165 * pi, -0.25 * pi)):(3.5 * sin_seg(\$1, 0.165 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 6, 4
set output "hmc_chain_cartoon2.eps"

unset border

unset xtics
set xrange[-5:5]

unset ytics
set yrange[-5:5]

set arrow from -4.75, 0 to 4.75, 0 lw 2 lc rgb "black" nohead back
set label "q" at 5, 0 center

set arrow from 0, -4.75 to 0, 4.75 lw 2 lc rgb "black" nohead back
set label "p" at 0, -5 center

set obj ellipse at 0, 0 size 1.0, 1.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 2.0, 2.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 3.0, 3.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 4.0, 4.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 5.0, 5.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 6.0, 6.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 7.0, 7.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 8.0, 8.0 lw 5 fs empty border lc rgb "#D3D3D3"
set obj ellipse at 0, 0 size 9.0, 9.0 lw 5 fs empty border lc rgb "#D3D3D3"

set arrow from 3 * cos(0.55 * pi), 3 * sin(0.55 * pi) to 3 * cos(0.55 * pi), sin(0.4 * pi) - 0.05 \
lw 3 lc rgb "$light" head filled size screen 0.01, 35 front
set arrow from 1 * cos(0.4 * pi), sin(0.4 * pi) to 1 * cos(0.4 * pi), 4.225 * sin(0.4 * pi) - 0.05 \
lw 3 lc rgb "$light" head filled size screen 0.01, 35 front
set arrow from 4 * cos(0.225 * pi), 4 * sin(0.225 * pi) to 4 * cos(0.225 * pi), 1.75 \
lw 3 lc rgb "$light" head filled size screen 0.01, 35 front

set arrow from 3 * cos(0.55 * pi) - 0.1, 3 * sin(0.55 * pi) - 0.02 \
to 3 * cos(0.55 * pi), 3 * sin(0.55 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set arrow from 1 * cos(0.4 * pi) - 0.1, 1 * sin(0.4 * pi) + 0.0275 \
to 1 * cos(0.4 * pi), 1 * sin(0.4 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set arrow from 4 * cos(0.225 * pi) - 0.1, 4 * sin(0.225 * pi) + 0.115 \
to 4 * cos(0.225 * pi), 4 * sin(0.225 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set arrow from 3.5 * cos(-0.085 * pi) + 0.06, 3.5 * sin(-0.085 * pi) + 0.25 \
to 3.5 * cos(-0.085 * pi), 3.5 * sin(-0.085 * pi) lw 3 lc rgb "$dark" \
head filled size screen 0.01, 35 front

set samples 100    # X Samples for ++
set isosamples 100  # Y Samples for ++

cos_seg(x, th1, dth) = cos( dth * (x + 5) / 10.0 + th1)
sin_seg(x, th1, dth) = sin( dth * (x + 5) / 10.0 + th1)

plot \
'+' using (3.0 * cos_seg(\$1, 0.8 * pi, -0.25 * pi)):(3.0 * sin_seg(\$1, 0.8 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle, \
'+' using (1.0 * cos_seg(\$1, 0.65 * pi, -0.25 * pi)):(1.0 * sin_seg(\$1, 0.65 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle, \
'+' using (4.0 * cos_seg(\$1, 0.475 * pi, -0.25 * pi)):(4.0 * sin_seg(\$1, 0.475 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle, \
'+' using (3.5 * cos_seg(\$1, 0.165 * pi, -0.25 * pi)):(3.5 * sin_seg(\$1, 0.165 * pi, -0.25 * pi)) \
w l lw 3 lc rgb "$dark" notitle

END
