#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal pdfcairo transparent enhanced size 6in, 4in font 'Times,35'
set output "energy_marginal_narrow.pdf"

set border 3

unset xtics
set xlabel "E - <E>"
set xrange [-15:15]

unset ytics
set ylabel ""
set yrange[0:0.2]

alpha1 = 80
beta1 = 4
mean1 = alpha1 / beta1

alpha2 = 88
beta2 = 4.4
mean2 = alpha2 / beta2

set samples 500

set style fill transparent solid 0.75

set label "{/Symbol p}_{ E | q}" at 6, 0.15 center tc rgb "$dark_highlight"
set label "{/Symbol p}_{ E}" at 7, 0.05 center tc rgb "$light_highlight"

plot \
beta2 ** alpha2 * (1 - x + mean1)**(alpha2 - 1) * exp(-beta2 * (1 - x + mean1)) / gamma(alpha2) \
w filledcurve lt 1 lw 1 lc rgb '$dark_highlight' notitle, \
beta1 ** alpha1 * (1 - x + mean1)**(alpha1 - 1) * exp(-beta1 * (1 - x + mean1)) / gamma(alpha1) \
w filledcurve lt 1 lw 1 lc rgb '$light_highlight' notitle

END

gnuplot << END

set terminal pdfcairo transparent enhanced size 6in, 4in font 'Times,35'
set output "energy_marginal_wide.pdf"

set border 3

unset xtics
set xlabel "E - <E>"
set xrange [-15:15]

unset ytics
set ylabel ""
set yrange[0:0.2]

alpha1 = 20
beta1 = 1
mean1 = alpha1 / beta1

alpha2 = 80
beta2 = 4
mean2 = alpha2 / beta2

set samples 500

set style fill transparent solid 0.75

set label "{/Symbol p}_{ E | q}" at 6, 0.15 center tc rgb "$dark_highlight"
set label "{/Symbol p}_{ E}" at 9, 0.05 center tc rgb "$light_highlight"

plot \
beta2 ** alpha2 * (1 - x + mean1)**(alpha2 - 1) * exp(-beta2 * (1 - x + mean1)) / gamma(alpha2) \
w filledcurve lt 1 lw 1 lc rgb '$dark_highlight' notitle, \
beta1 ** alpha1 * (1 - x + mean1)**(alpha1 - 1)* exp(-beta1 * (1 - x + mean1)) / gamma(alpha1) \
w filledcurve lt 1 lw 1 lc rgb '$light_highlight' notitle

END
